spring.application.name=520_microProgEventos
#server.port=8090
app.microservices.tematicas.url=http://localhost:8081/tematicas/{numPersona}
app.microservices.tematicas.url.erronea=http://localhost:8081/tematicas/A
#
qtx.progEventosService.messageBroker.host=localhost
qtx.progEventosService.messageBroker.exchangeEvtos=eventosNuevos